### ISSUE TITLE
macOS: ld: library not found for -lrt

### ISSUE THREAD

**Issue by automactic** [kiwix/kiwix-build#17]
on macOS, build natively, encountered the following error
[lrt_error.txt](https://github.com/kiwix/kiwix-build/files/825006/lrt_error.txt)

Quote comment by @mgautierfr in issue #9 
> For what I see, clang cannot found librt. The flag -lr comes from the xapian pkg-config if the configure detect (and found) the timer_create function. This part was a bit buggy and I fix it with the e6673e2.
> Try to remove all xapian and kiwix-tools stuff (SOURCE and BUILD) and launch a new compilation.
If it doesn't work, you will have to fix xapian (first find if you really need librt, and then find either why xapian add it or why kiwix-tools cannot found it)

The question is:
- I assume @mgautierfr means `-lrt` is carried from xapian. (There was no flag `-lr`) If this is true, how come xapian build successfully?
- How do I know if librt is needed? I don't know what it does and how xapian use it

**Comment by mgautierfr** [comment]
Rereading your compilation logs, I've seen that the `-lrt` flags come at the end of the command line and so does not come from xapian pkg-config itself.
If fact it comes from kiwix-tools compilation system itself : https://github.com/kiwix/kiwix-tools/blob/a3a0127edb40df243f08f3de48975fa45f46b964/meson.build#L15-L23

I think those series of lines are no more necessary with the last patches I've made on xapian part.
So we should simply remove them. Can you try on your side to remove them and recompile ?
(Just remove the lines in the kiwix-tools repository in the `SOURCE` directory) and relaunch `kiwix-build.py`)

-------
I was writing a long post to explain you what I've done on the xapian part when I found what I've explained above. It is no more really relevant (especially the last part) because it is probably a bug in kiwix-tools build-system but it is still true so I keep it here :

Xapian checks if `librt` is available and compile with it if it is present. The check is made here (https://github.com/xapian/xapian/blob/master/xapian-core/configure.ac#L421-L437)

However, even if xapian link with `librt`, the released version of xapian do not add the `-lrt` flag in the pkg-config file, and then, other compilations (as `kiwix-tools`) fail because of `undefined symbols`.

So, I've made a patch to add the `-lrt` flag when necessary. This patch is patches/xapian_pkgconfig.patch in kiwix-build repository. The present version on master is bugged, I'd discovered it while cross-compiling for android and so, there is another (better) version on `android` branch. The commit for the fix is df62eea.

This is why I told you to try to recompile xapian with the `android` branch. To see if the last version of my patch is good enough.

If the `-lrt` flag is present in you compilation option but the compiler can't find it, this is either a bug in my patch (`librt` is not present and I the flag anyway) or a bug somewhere else (`librt` is present, xapian detect it but other compilation steps cannot).
What you can do is have a look on the log files (either in the `LOGS` directory of kiwix-build or in the xapian's `config.log` in `BUILD_native_dyn/xapian-1.4.2` to see if xapian inded link with the `librt`.

**Comment by mgautierfr** [comment]
@automactic Just to mention that I've merged the `android` branch into `master`. So the last version of xapian patch is in `master` now. You can rebase your `apple_platforms` onto `master` now.

**Comment by automactic** [comment]
This now seems to build correctly without errors
