### ISSUE TITLE
Add Flatpak support

### ISSUE THREAD

**Issue by birros** [kiwix/kiwix-build#249]
Hello 😊

I spent the late afternoon diving into your build system, it's very well designed, however I'm not sure how to integrate Flatpak support.

**Is the following overview going in the right direction or am I going the wrong way?**

The most difficult part is generating the manifest from dependencies, which may require adding additional information to other dependency declarations.

Generating the manifest in this way will facilitate its reuse when the time comes to deploy Kiwix on Flathub.

Compiling dependencies and integrating them using a method similar to the one used for Android platforms would make the task more complex and would not be reusable on Flathub. The good practice being to provide the manifest listing the sources so that Flathub can compile itself.

I'm not sure I can do it, the task seems very complex, it will depend if I find the time and energy to do it 😉

```
# kiwixbuild/packages.py:

'debian_flatpak': {
  'COMMON': ['flatpak', 'flatpak-builder']
},
'fedora_flatpak': {
  'COMMON': ['flatpak', 'flatpak-builder']
}



# kiwixbuild/dependencies/flatpak.py:

class flatpak
  class Source
    run_command
      flatpak remote add flathub ...
      flatpak install flathub org.kde.Sdk//5.11 ...
  NoopBuilder



# kiwixbuild/platforms/flatpak.py:

class FlatpakPlatform
  toolchain_names = ['flatpak']
  compatible_hosts = ['fedora', 'debian']



# kiwixbuild/dependencies/base.py:

class FlatpakBuilder
  configure

    **Build the manifest in json format from a
    template and based on the dependency graph**

    run_command
      flatpak-builder --download-only builddir manifest.json
  compile
    run_command
      flatpak-builder builddir manifest.json
  make_dist
    run_command
      flatpak-builder --export-only --repo=repo builddir manifest.json
      flatpak build-bundle repo kiwix.flatpak org.kiwix.Client



# kiwixbuild/dependencies/kiwix-desktop-flatpak.py:

class KiwixDesktopFlatpak
  NoopSource
  FlatpakBuilder
    dependencies = ['kiwix-desktop']
```

**Comment by mgautierfr** [comment]
> I spent the late afternoon diving into your build system, it's very well designed

Thanks ;)


I see different ways to implement flatpak support in `kiwix-build`. They are not all mutually exclusive (nor good ideas)

1. Use a small flatpak manifest just running `kiwix-build kiwix-desktop`. This is somehow the easiest way to have flatpak package for kiwix-desktop. But this is also the solution I dislike the most. It excludes most of the flatpak-builder feature like caching and so.
2. Have `kiwix-build` directly build everything in a "flatpak container" using `flatpak build*` commands. This is somehow reimplement flatpak-builder reusing the existent `kiwix-build` system (dependencies resolution, archive downloading, compilation options, ...). This idea is pretty attractive as it totally integrate with `kiwix-build`. No extra step, exact same compilation options used inside and outside of flatpak, etc. However, I fear a bit that it is more complex than just `flatpak build-init`, `flatpak build foo`, `flatpak build-finish` and we could have some surprises. And of course, this doesn't work with flathub.
3. Generate the manifest with `kiwix-build` and let flatpak-builder build everything. By generating the manifest, we should be able to correctly control what we build and keep the manifest up-to-date with our settings. I see two way to generate the manifest :
 - Have a new dependency using a custom builder (the way you seem to follow). It avoid big changes in `kiwix-build` but it will need a lot of code in the builder and you will end to reimplement a lot of things already in `kiwix-build` (dependencies resolution and ordering, resolution of the compilation commands/options, ...)
  - Introduce the notion of backend in `kiwix-build` and have a new flatpakManifest backend. The flatpak platform setting the backend to flatpakManifest. Everything else in `kiwix-build` would (almost) not be modified and it would be the job of flatpakManifest to implement the `run_command` and `download` methods to print the command in the manifest instead of actually running them. It would avoid a lot of reimplementation of base functionality but at cost of more change in the low level part of `kiwix-build`.

Introducing the notion of backend is my preference. It a bit of work but it is the solution that would produce the cleaner code. And it would open ways to a lot of cool thing (as implementing the solution 2 for flatpak, porting `kiwix-build` to windows or running things in docker, chroot, bubblewrap, buildstream ...)

---
Not especially related to flatpak, but I have to write it somewhere :)
When we start to work on `kiwix-build`, @kelson42 mentions the idea to have/create a "meta build-system" independent of kiwix and have kiwix projects just using this build system with the right configuration. I was again this because we were just needing a "small" system to run our things we our setting and I didn't want to maintain a separated project on my own.
But time passes and I start to change my mind. `kiwix-build` became a complex tools being able to download/configure/build different projects, handling dependencies, different build-systems (autotols, cmake, meson, ..) and cross-compilation for different platforms. It definitively became a tool that could be useful for others and it may worth to move it to an independent project

If we implement the notion of backend to be able to run kiwix-build on windows (and we have to support windows), flatpak and so, I think it worth it to at least ask ourselves about moving to a separated project.

**Comment by kelson42** [comment]
This has been done, we need now to publish it on Flathub, see #281
