### ISSUE TITLE
Automatically install ninja

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-build#28]
It's not compulsory, but would simplify the installation by avoiding some manual steps

**Comment by julianharty** [comment]
Yes please. When I followed the steps in this project's README for ninja it took me several goes and at least 30 minutes to get something working...

**Comment by kelson42** [comment]
@mossroy @julianharty Ninja (and meson) is now packaged By recent Debian/Ubuntu, people should be use the package than install it manually. Would not that be good enough?

**Comment by TechnologyClassroom** [comment]
My distribution came with an old version of ninja.

Here is the bash snippet, I used to compile ninja for kiwix-build:

```
echo "Cloning ninja repository..."
cd /tmp
git clone https://github.com/ninja-build/ninja
cd ninja/
echo "Creating the ninja binary..."
./configure.py --bootstrap

echo "Checking if ninja was successfully built from source..."
if [ $(./ninja -h 2>&1 | wc -l) -gt 1 ]
then
  echo "ninja compiled successfully!"
else
  echo "ninja failed to compile :("
  echo "Check logs for more information"
  exit 1
fi

echo "Creating ~/bin if it does not exist..."
mkdir -p $HOME/bin
echo "Copying ninja to ~/bin..."
cp ninja $HOME/bin
```

**Comment by kelson42** [comment]
After thinking twice (at least) about it, I think I'm pretty against because:
* It would significantly complicate the code, a full module should be focus on installing Ninja (and then why not Meson, etc.)
* I'm really not sure this is is so necessary. Packages makes good progresses and if by any chance this is not available (or an older version) then installing a newer version is not a big deal (at least on GNU/Linux).

I will make a PR giving direct links to Meson & Ninja projects to make it a bit easier (the whole README should be improved) and IMO this is probably the best thing to do now.
