### ISSUE TITLE
does not update kiwix-lib automatically

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-build#378]
With a working kiwix-build using libkiwix `7.0.0`, I naively tried to `git pull` and relaunch `kiwix-build`.

It worked but still produced libkiwix `7` while version `8` had been released and referenced in `versions.py`.

* should it have automatically picked-up version 8 and compiled latest version? In this case it's a bug (noticed some modified files in source folder)
* should I have done anything for that expected behavior to happen? I ended-up removing `SOURCES/kiwix-lib`. In this case, we should mention it in README.

**Comment by kelson42** [comment]
We have already many tickets/bugs around this kind of problem. Really hope we can get rid of that in January.

**Comment by mgautierfr** [comment]
What is done is mostly `git fetch origin master && git checkout master`
It's work well on clean repository but obviously it just checkout the master branch and do not update against the `origin` remote.

There are those pretty old PRs https://github.com/kiwix/kiwix-build/pull/61 and https://github.com/kiwix/kiwix-build/pull/209 about this. The main important issue, is that don't want to move back to `origin/master` when the repository is on another branch or with dirty working tree. We (I) want to be able to change the source and launch kiwix-build to test my changes, if we always checkout to `origin/master`, we cannot.

Saying that :
- There is the option `--make-release` that create a separate source directory (kiwix-lib_release) and checkout the version referenced in `version.py` instead of `master`. If you want to build a release version, you should use it (it also build project in release mode). 
- There is the options `--skip-source-prepare` to make kiwix-build do nothing about the sources (no download of release archives, no clone/checkout, no patch, ...), just build as it is.

**Comment by rgaudin** [comment]
Ah OK, I think those are more than enough. I think we should be more explicit about `--make-release` use case in README/help but I don't have a suggestion ATM.

**Comment by mgautierfr** [comment]
I reopen the issue.
This is a "real" problem. We must fix this one way or another. There are already two PR for this.
(And this is probably the same problem with `--make-relase`, it may be necessary to delete the directory `kiwix-lib_release` by hand.)

**Comment by mgautierfr** [comment]
With last change in #413 :
- Normal behavior (without `--make-release`) is ok (update if possible, no update if change in the source directory)
- Release behavior do not update to last version (the local directory is a `detached head` state so we cannot update the branch) but there is explicit warning about this.

I think it is enough as most of the time the release is made by the CI (and so, on a clean directory).
