### ISSUE TITLE
If local source code has been modified, it should not be reseted by rebuilding

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#395]
See https://github.com/kiwix/kiwix-build/issues/346#issuecomment-566582417

**Comment by Aditya-Sood** [comment]
_Gist of the issue:_ The local modifications to the code of a dependency (like kiwix-lib) will be made on a branch different from `master` of kiwix-lib. However, upon copying this local repository to the SOURCE directory of kiwix-build, the locally made changes will be ignored since the build process automatically checks-out the `master` branch of kiwix-lib.

The workaround I used was to temporarily merge the `local-changes-branch` into `master`, copy the kiwix-lib repository into kiwix-build's SOURCE directory for building kiwix-lib, and then roll back the merge with master.
Maybe some better alternative is possible which wouldn't require merging into master and then rolling-back?
