### ISSUE TITLE
Upgrade NDK in kiwix-build

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-build#544]
Please upgrade the ndk version r21b , its being required for android aar for  libkiwix build 11.0.0.

**Comment by MohitMaliFtechiz** [comment]
hi @mgautierfr ,

We required ```r21b``` its the lease version  android studio is supporting . Android studio not building projects which is lower then this verision its still not latest when latest one was ```r25b``.

**Comment by mgautierfr** [comment]
A lot of things have changed between `r13b` and `r21b`.
Some of them are really important (From https://developer.android.com/ndk/downloads/revision_history):
- Support of Gcc has been removed in `r18b`. We must now use clang to compile. Our current CI is based on docker images which don't contain clang.
- `libc++` is now the default standard library in `r17c` instead of `stdlibc++`.
- Move to unified headers. May need to adapt our includes (https://android.googlesource.com/platform/ndk/+/ndk-release-r16/docs/UnifiedHeadersMigration.md)

This is a not a simple move as changing the version number in a config file 😞

**Comment by kelson42** [comment]
@MohitMaliFtechiz If we keep old ndk, what are exactly the consequences?

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 @mgautierfr ,

Currently problem with ```r13b``` is that this is not more supported by the android studio , @mgautierfr I have build the code on local for libkiwix successfully for minimum target 24. so you just need to do some refactoring so that its support minimum target 21. Last time its was error due ```fseeko``` I don't remember the error.

**Comment by mgautierfr** [comment]
> so you just need to do some refactoring so that its support minimum target 21. Last time its was error due fseeko I don't remember the error.

I've got the same error. How did you fix it ?

**Comment by mgautierfr** [comment]
I've succeeded to build with ndk r21b, but I had to change the api to 24 (was 21 for 64bits and 14 for 32 bits).
What is the impact of upgrading to api 24 ? How many users are impacted ?

> so you just need to do some refactoring so that its support minimum target 21

It seems the error are the stdlib. We may miss use the ndk (with wrong define/option) but it is not in our code.

**Comment by MohitMaliFtechiz** [comment]
hi @mgautierfr ,

I have tried to build the libkiwix.so using command line without using android studio, I think i can build it with older NDK with command line only. I will update you the result.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz is r21e good for you? Would that fix your problems?

Yes r21b with minimum target 21 is good for me.
