### ISSUE TITLE
Move out of bionic.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-build#691]
This is a tracking issue to move out of bionic build.

We still need to build libzim on bionic because we need to compile on glibc <= 2.28. This is enforced by the python "platform" definition and the last available platform is `manylinux_2_28`
(See original issue https://github.com/kiwix/kiwix-build/issues/595).

However:
- Bionic's eol is April, 2023 
- Python 3.6 (which is the python version in Bionic) is eol December 2018.

There was the deadsnake ppa (https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa) to install a "recent" python 3.8 on Bionic but it seems the repository for Bionic is no more (probably with Bionic's eol)

This means that kiwix-build is stuck with python 3.6, a 6 years old dead version.

A recent issue on manylinux is tracking the `manylinux_2_34` status : https://github.com/pypa/manylinux/issues/1585. Hopefully we will able to move to a more recent version of ubuntu soon.

Another way is to build libzim directly using `manylinux_2_28` as the image contains python up to 3.12

**Comment by rgaudin** [comment]
I understand the problem as:

- we need bionic because we publish pylibzim for manylinux_2_28 (see https://github.com/openzim/python-libzim/issues/170#issuecomment-1660836831)
- bionic-related files have been removed from the PPA so we cannot rebuild our bionic image to update it.
- without the PPA, bionic is limited to python 3.6
- kiwix-build code is 3.8+

Possible solutions:

- ❌ publish pylibzim for manylinux_2_31. There is no image and manylinux is looking at creating one for 2_34. We don't know when and [it wont support bullseye](https://sourceware.org/glibc/wiki/Release)
- install recent python from source inside our bionic image
- build (kiwix-build) inside manylinux_2_28

@mgautierfr I think it's up to you. I can't think of any strong reasons in favor of one or the other. Added this topic to the hackathon (broader topic) should we have not decided by then

**Comment by kelson42** [comment]
The CD fails on this looks like, see https://github.com/kiwix/kiwix-build/actions/runs/9387683596/job/25851190286#step:6:325
