### ISSUE TITLE
macOS: cannot run kiwis-build.py

### ISSUE THREAD

**Issue by automactic** [kiwix/kiwix-build#7]
Hi @mgautierfr, I am trying to run the build script on macOS 10.12.3, with python 3.6, targeting macOS.
I executed `sudo python3 kiwix-build.py --build-static build`, got the following error message `ERROR: kiwix-build is intented to run only on Linux platform`
What should I do?

**Comment by mgautierfr** [comment]
Hi @automactic, the last version on master should allow you to run the script.

This was mainly to avoid user to run `kiwix-build.py` on Windows but I forgot about macOS :/ . Now, it should just warn instead of exit.

As a side comment, you should not run `kiwix-build.py` with `sudo`, most of the time, it's a bad habit to run compilation with `root` right (especially if it is not tested). If we want to install in a directory writable only by `root` (`/usr/local`, ...), we should update `kiwix-build.py` to launch the `install` steps only with `sudo`.
