### ISSUE TITLE
Nightly Latest folder empty or has unique names

### ISSUE THREAD

**Issue by darkenvy** [kiwix/kiwix-build#92]
The nightly folder at http://download.kiwix.org/nightly/latest/ is empty a lot of times. When the folder is not empty, the filenames can be unique, causing scripts or docker builds to fail.

If the names in nightly/latest/ are always the same, then we can always point our software towards the latest build. Which is most helpful when we are all submitting bug reports. 

**desired:**
`http://download.kiwix.org/nightly/latest/kiwix-tools_linux64.tar.gz`

**actual:**
`http://download.kiwix.org/nightly/latest/kiwix-tools_linux64_2017-11-12.tar.gz`
or sometimes blank:
`http://download.kiwix.org/nightly/latest/`

**Comment by mgautierfr** [comment]
> The nightly folder at http://download.kiwix.org/nightly/latest/ is empty a lot of times

The problem is that the creation of this directory (actually a simlink) and the creation of the content inside it are made by different script (one for the directory and several for the content)

The different nightly things are created by different scripts on CI and we cannot really choose when those script are run. If you look in the directory before those scripts have run, there will be no content.

> If the names in nightly/latest/ are always the same, then we can always point our software towards the latest build

I really like the fact to have to date of the nightly build somewhere. There are a lot of person testing kiwix-build with nightly (and that's good) and it is important to have to exact date in bug report.
If we remove this information, we can be pretty sure that we will never have the exact date of kiwix-serve tested.

We could add the date in the name of the binaries inside of the archive instead of in the archive's name itself, but I is probable that your script will simply fails later when trying to launch the binary.

**Comment by holta** [comment]
> I really like the fact to have to date of the nightly build somewhere.

Me too!

Idea: Keep the dates in the nightly directories+filenames BUT ALSO establish unchanging names in http://download.kiwix.org/nightly/latest/ that always pointing to the very latest &mdash; if this is doable!

PS WordPress uses a dynamic redirect @ https://wordpress.org/latest.tar.gz to accomplish this: the actual file you download contains the exact version number thankfully :)

**Comment by kelson42** [comment]
Will try to have a look to that.

**Comment by darkenvy** [comment]
Thanks @mgautierfr, @kelson42 . Much appreciated

**Comment by kelson42** [comment]
We have removed the `latest` directory in an attempt to make things more simple. So this ticket in invalid now.
